name: Train and Report (CML)

on:


  pull_request:
    branches: ["main"]

permissions:

  pull-requests: write
  contents: read

jobs:
  run-experiment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup CML
        uses: iterative/setup-cml@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download data
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.namename }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.secret }}
        run: dvc pull

      - name: Train model
        run: dvc repro

      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Результаты эксперимента" > report.md

          echo "" >> report.md
          echo "### Изменения параметров" >> report.md
          dvc params diff main --md >> report.md

          echo "" >> report.md
          echo "### Изменения метрик" >> report.md
          dvc metrics diff main --md >> report.md

          cat report.md

          cml comment create report.md